export type ClarityLang = "en" | "he";

export const COPY = {
  en: {
    product: "Clarity",
    startEyebrow: "For your store",
    startTitle: "Your store, as questions and answers",
    startBody:
      "We’ll read the store and turn it into questions and answers. You confirm what’s true, with a link to exactly where it appears on the site.",
    startSteps: ["Scan the store website", "Fill each question and answer, like a knowledge base", "Download the knowledge base"],
    urlLabel: "Store website",
    urlPlaceholder: "yourstore.com",
    urlHint: "Paste the homepage — with or without https. Example: yourstore.co.il",
    scanCta: "Scan the store",
    demoCta: "See a sample",
    scanningTitle: "Reading the store…",
    scanningBody: "We’re reading the store and filling answers from what’s actually written.",
    scanSteps: [
      "Opening the homepage",
      "Reading all products and collections",
      "Reading about, shipping, returns, payment, and similar pages",
      "AI fills answers per category from the site",
    ],
    reviewEyebrow: "Your turn",
    reviewTitle: "What is true in your store?",
    reviewBody: "Fill the answers. Edit anything the AI got wrong.",
    conflict: "Check",
    clear: "Consistent",
    unclear: "Needs a clearer sentence",
    missing: "Missing on site",
    missingBody: "This is missing on the site. Write one clear sentence for customers.",
    suggestedPage: "Suggested page",
    foundPage: "Section page",
    true: "True",
    notTrue: "Not true",
    sources: "Found on",
    doThisNow: "Your turn",
    doThisSteps: "Fill each answer. Skip anything that doesn’t apply.",
    draftEyebrow: "Questions & answers",
    draftTitle: "What is true in your store?",
    draftBody: "Same structure as the knowledge base: category, section, question, answer. Fill or edit freely.",
    editAnswer: "Edit",
    saveEdit: "Save",
    editBoxHint: "Edit the answer here",
    categoriesNav: "Categories",
    emptyCategory: "Nothing in this category yet.",
    openBody:
      "Free-form questions that don’t fit the other categories. Add your own, or scan this category so AI can pull extras from the site.",
    processesBody:
      "Service playbooks: the steps, and exactly what to collect from the customer to start or finish. Write them even if they’re not on the site.",
    processesSection: "Processes",
    writeExample: "Example wording",
    processWriteHint: "Write the process even if it isn’t on the website.",
    writeProcess: "Write the process",
    infoTab: "Info",
    processTab: "Process",
    addQuestion: "Add a question",
    optionalQuestion: "Question (optional)",
    newQuestion: "Question",
    newAnswer: "Answer",
    forCustomers: "Customers + agents",
    agentOnly: "Agents only",
    insertFromSite: "From the site — tap to insert",
    scanSuggestion: "Suggested from the scan",
    restoreItem: "Restore",
    skippedFold: "Not relevant",
    questionPlaceholder: "Write the question…",
    answerPlaceholder: "Write the answer…",
    collectHint: "Tap what you need to collect from the customer",
    collectOther: "Another field…",
    collectOtherAdd: "Add",
    sectionConflicts: "Check what’s true",
    sectionFound: "What we found",
    sectionMissing: "Missing on the site",
    sectionMissingHint: "Optional. Skip for now, or write one sentence.",
    continueBlocked: "Fill each answer, or skip what doesn’t apply",
    questionConflict: "A few versions showed up. Tap True or Not true.",
    questionMissing: "The site doesn’t say this. What is true in your store?",
    questionClear: "This is what we found. Is it still true?",
    questionUnclear: "This is incomplete. Write one clear sentence.",
    seeExactPlace: "See exactly where this appears",
    sourceSheetTitle: "Where it appears",
    sourceHighlightHint: "The exact sentence is highlighted in yellow. Tap below to jump to it on the page.",
    jumpToHighlight: "Scroll to the exact place",
    openExactPlace: "Open the live page",
    closeSource: "Close",
    chooseThis: "This is the true one",
    previewLoading: "Loading the page…",
    writeYourself: "Or write it yourself if nothing above is right",
    writeYourselfCta: "Write it yourself",
    notRelevant: "Not relevant to my store",
    hiddenRejected: "sentences marked not true are hidden",
    showRejected: "Show them",
    hideRejected: "Hide them",
    saveNext: "Save & continue",
    backSection: "Back",
    chooseFirst: "Tap or write what’s true",
    markedTrue: "Marked true",
    markedFalse: "Marked not true",
    contradictsBadge: "Another version",
    sureTitle: "Are you sure?",
    sureRejectBody: "You marked this as true:\n“{approved}”\n\nMark this other sentence as not true?",
    sureApproveBody: "You already marked something else as true:\n“{approved}”\n\nMark this one true too? You still choose what to keep, reject, or edit — nothing else changes automatically.",
    sureRejectCta: "Yes, this is not true",
    sureApproveCta: "Yes, this is also true",
    sureKeepCta: "No, leave it",
    sureCancel: "Cancel",
    recommendation: "Suggested wording",
    canonicalLabel: "Source-of-truth sentence",
    canonicalPlaceholder: "Write the sentence customers — and AI — should rely on.",
    writeHere: "What to write here",
    aiWhyLabel: "Why this matters for AI",
    foundOnSite: "What we found on the site",
    downloadSection: "Download this section",
    copySection: "Copy this section",
    nextSection: "Next section",
    sectionReady: "This section is ready when the source-of-truth sentence is written.",
    downloadHint: "Download this section when it’s done. At the end, download the full knowledge base.",
    openPage: "Open page",
    pagesRead: "pages read",
    all: "All",
    conflicts: "Versions",
    missingFilter: "Missing",
    approved: "Approved",
    pending: "To review",
    knowledgeCta: "See your page",
    backToReview: "Back to review",
    knowledgeEyebrow: "Knowledge base",
    knowledgeTitle: "Download your knowledge base",
    knowledgeBody:
      "Every question and answer you confirmed — with a link to exactly where it appears on the site.",
    publishStepsTitle: "What to do now",
    publishStep1: "Review each answer and mark True, Not true, or Edit",
    publishStep2: "Use the page link and “See exactly where this appears” next to each question",
    publishStep3: "Download the knowledge base when you’re done",
    copyPage: "Copy page HTML",
    downloadPage: "Download HTML",
    copyKb: "Copy JSON",
    copied: "Copied",
    downloadKb: "Download JSON",
    downloadTxt: "Download text",
    downloadPdf: "Download PDF",
    exportTitle: "Your knowledge base",
    exportBody: "Download everything in the Gemini format — JSON, text, or PDF.",
    exportTitleDone: "Download everything",
    exportBodyDone: "Same Gemini knowledge-base format: JSON for import, text, or PDF.",
    printPdfHint: "In the print window choose Save as PDF.",
    downloadMenu: "Download",
    guideCta: "How it works",
    guideTitle: "What to do here",
    guideBody: "Clarity reads the store and turns it into questions. You only confirm what’s true — then download the knowledge base.",
    guideSteps: [
      "Scan the store website, or continue an existing draft.",
      "For each item: True, Not true, or Edit — then tap Save.",
      "Next to each question: a link to the page, and “See exactly where this appears”.",
      "When you’re done, tap Download at the top: JSON, text, or PDF.",
    ],
    guideGotIt: "Got it",
    pagePreview: "Page preview",
    pagesToDelete: "Pages to delete from the site",
    pagesToDeleteBody: "These pages scatter the same information — or still say something you marked as not true. Remove them after the new page is live.",
    productCleanupTitle: "Clean the products",
    productCleanupBody:
      "We found policy text on {n} products. Delete it from the descriptions — shipping and returns belong on the one info page.",
    productCleanupDownload: "Download the cleanup list",
    removeFromProduct: "Delete from this product",
    productCleanupExamples: "See examples",
    suggestedPath: "Suggested URL",
    siteFixes: "Pages to update on the site",
    siteFixesBody: "These pages still say something you marked as not true. Suggested replacement:",
    pagesToCreate: "Sections to add on the site",
    pagesToCreateBody: "These sections are missing. Add the page, then use this wording.",
    emptyKb: "Approve at least one sentence to build the knowledge base.",
    rescan: "Scan a different store",
    saveDraft: "Save draft",
    draftSaved: "Draft saved",
    draftSavedHint: "Not signed in — this is saved only in this browser.",
    draftSavedCloudHint: "Saved to your account.",
    draftSaveCloudError: "Couldn’t save to your account. Tap Save draft.",
    draftSavedAt: "Saved to your account · {time}",
    signInGoogle: "Continue with Google",
    signOut: "Sign out",
    signInTitle: "Sign in to Clarity",
    signInBody: "Create an account or sign in. Then you can scan a store and save a draft.",
    signInHint: "Sign in to continue.",
    signInCta: "Sign in",
    authOr: "or username & password",
    authLogin: "Sign in",
    authRegister: "Create account",
    authLoginCta: "Sign in",
    authRegisterCta: "Create account",
    authUsername: "Username",
    authPassword: "Password",
    authWorking: "One moment…",
    authFailed: "Couldn’t sign in. Try again.",
    authBadLogin: "Wrong username or password.",
    authTaken: "That username is already taken.",
    authWeakPassword: "Password must be at least 6 characters.",
    authInvalidUsername: "Use 3–40 letters, numbers, . _ -",
    authNoDatabase: "Account storage isn’t connected yet. Try again in a minute.",
    topicQuestionsCount: "{n} questions",
    addedQuestions: "Questions you added",
    savingCloud: "Saving to your account…",
    productSectionBody: "Mark what’s relevant on products, and what should be edited.",
    productEditHint: "What to edit on this product",
    productNotes: "Notes for this product…",
    downloadDraft: "Download draft file",
    adminCta: "All answers",
    adminTitle: "Merchant answers",
    adminBody: "Every Clarity questionnaire, including deleted ones. Download JSON per store or everything together.",
    adminEmpty: "No questionnaires yet.",
    adminDeleted: "Deleted from their list",
    adminDownloadOne: "Download JSON",
    adminDownloadAll: "Download all",
    adminForbidden: "You don’t have access to this page.",
    categoryScan: "Scan this category",
    categoryScanning: "Scanning this category…",
    categoryScanDone: "Focused scan done. Check True / Not true, and fill anything still missing.",
    categoryScanMissing: "Focused scan done. {n} questions still have nothing on the site — write them or mark Not true.",
    categoryScanNoAi: "Found what was on the site. Add a Gemini or OpenAI key to let AI fill missing answers.",
    categoryScanError: "Couldn’t scan this category. Try again.",
    draftsTitle: "Your drafts",
    draftsEmpty: "No drafts in this account yet. Use the same sign-in method as on the other device — Google and username are separate accounts.",
    signedInAs: "Signed in as {name}",
    resumeDraft: "Continue",
    deleteDraft: "Delete",
    deleteDraftTitle: "Delete this questionnaire?",
    deleteDraftBody: "It will leave your list, but stay saved in the account.",
    deleteDraftConfirm: "Yes, delete",
    deleteDraftCancel: "Cancel",
    backToDrafts: "Back to drafts",
    viewScroll: "Scroll",
    viewSlides: "Slides",
    progressDone: "{done} of {total} done",
    progressLeft: "{n} left",
    sectionComplete: "Section complete!",
    allComplete: "You finished everything!",
    prevSection: "Previous",
    nextItem: "Next",
    prevItem: "Back",
    importDraft: "Load a draft or knowledge-base JSON",
    draftPages: "{n} pages",
    draftJustNow: "Just now",
    errorTitle: "We couldn’t finish the scan",
    errorInvalid: "Enter a valid store website, like yourstore.com or yourstore.co.il.",
    errorPrivate: "That address can’t be scanned.",
    errorUnreachable: "We couldn’t reach that website. Check the spelling, or try with www / without www.",
    errorBlocked: "The site blocked automated access. Try without www, or the Shopify address (yourstore.myshopify.com).",
    errorTimeout: "The site took too long to respond. Try again in a moment.",
    errorEmpty: "The site opened, but there wasn’t enough text to read.",
    errorFailed: "The scan failed. Check the address and try again.",
    tryDemo: "See a sample instead",
    filterEmpty: "Nothing in this view yet.",
    demoBadge: "Sample store",
    langToggle: "עברית",
  },
  he: {
    product: "Clarity",
    startEyebrow: "לחנות שלכם",
    startTitle: "האתר שלכם — בשאלות ותשובות",
    startBody:
      "נקרא את האתר ונהפוך אותו לשאלות ותשובות. אתם מאשרים מה נכון, עם קישור למקום המדויק באתר.",
    startSteps: ["סרקו את האתר של החנות", "מלאו שאלות ותשובות כמו במאגר הידע", "הורידו את מאגר הידע"],
    urlLabel: "כתובת האתר",
    urlPlaceholder: "yourstore.co.il",
    urlHint: "הדביקו את עמוד הבית — עם או בלי https. למשל: yourstore.co.il",
    scanCta: "סרקו את החנות",
    demoCta: "ראו דוגמה",
    scanningTitle: "קוראים את האתר…",
    scanningBody: "קוראים את האתר וממלאים תשובות ממה שבאמת כתוב.",
    scanSteps: [
      "פותחים את עמוד הבית",
      "קוראים את כל המוצרים והקטגוריות",
      "קוראים אודות, משלוחים, החזרות, תשלום ודומיהם",
      "ה־AI ממלא תשובות לפי קטגוריה מתוך האתר",
    ],
    reviewEyebrow: "התור שלכם",
    reviewTitle: "מה נכון בחנות?",
    reviewBody: "מלאו את התשובות. עורכים מה שה־AI לא דייק.",
    conflict: "לבדיקה",
    clear: "עקבי",
    unclear: "צריך משפט ברור יותר",
    missing: "חסר באתר",
    missingBody: "זה חסר באתר. כתבו משפט אחד ברור ללקוחות.",
    suggestedPage: "עמוד מוצע",
    foundPage: "עמוד הסקשן",
    true: "זה נכון",
    notTrue: "זה לא נכון",
    sources: "נמצא ב",
    doThisNow: "התור שלכם",
    doThisSteps: "מלאו כל תשובה. דלגו על מה שלא רלוונטי.",
    draftEyebrow: "שאלות ותשובות",
    draftTitle: "מה נכון בחנות?",
    draftBody: "אותו מבנה כמו מאגר הידע: קטגוריה, סעיף, שאלה, תשובה. ממלאים או עורכים חופשי.",
    editAnswer: "עריכה",
    saveEdit: "שמור",
    editBoxHint: "כאן עורכים את התשובה",
    categoriesNav: "קטגוריות",
    emptyCategory: "אין עדיין שאלות בקטגוריה הזו.",
    openBody:
      "שאלות חופשיות שלא נכנסות לקטגוריות האחרות. הוסיפו בעצמכם, או סרקו את הקטגוריה כדי שה־AI ישלוף עוד מהאתר.",
    processesBody:
      "תהליכי שירות: השלבים, ומה בדיוק לאסוף מהלקוח כדי להתחיל או לסיים. כתבו גם אם זה לא מופיע באתר.",
    processesSection: "תהליכים",
    writeExample: "דוגמה לניסוח",
    processWriteHint: "כתבו את התהליך גם אם הוא לא כתוב באתר.",
    writeProcess: "כתבו את התהליך",
    infoTab: "מידע",
    processTab: "תהליך",
    addQuestion: "הוסיפו שאלה",
    optionalQuestion: "שאלה (לא חובה)",
    newQuestion: "שאלה",
    newAnswer: "תשובה",
    forCustomers: "ללקוחות ולסוכן",
    agentOnly: "לסוכן בלבד",
    insertFromSite: "מהאתר — לחצו להוסיף לתשובה",
    scanSuggestion: "המלצה מהסריקה",
    restoreItem: "החזירו",
    skippedFold: "לא רלוונטי",
    questionPlaceholder: "כתבו את השאלה…",
    answerPlaceholder: "כתבו את התשובה…",
    collectHint: "לחצו על סוגי המידע שצריך לאסוף מהלקוח",
    collectOther: "שדה נוסף…",
    collectOtherAdd: "הוסיפו",
    sectionConflicts: "בדקו מה נכון",
    sectionFound: "מה שמצאנו",
    sectionMissing: "חסר באתר",
    sectionMissingHint: "לא חובה עכשיו. אפשר לדלג, או לכתוב משפט אחד.",
    continueBlocked: "מלאו כל תשובה, או דלגו על מה שלא רלוונטי",
    questionConflict: "יש כמה גרסאות. סמנו נכון או לא נכון.",
    questionMissing: "האתר לא כותב על זה. מה נכון בחנות?",
    questionClear: "זה מה שמצאנו. זה עדיין נכון?",
    questionUnclear: "זה חלקי. כתבו משפט אחד ברור.",
    seeExactPlace: "ראו איפה בדיוק זה כתוב",
    sourceSheetTitle: "איפה זה באתר",
    sourceHighlightHint: "המשפט מסומן בצהוב. לחצו כדי לרדת בדיוק למקום בעמוד.",
    jumpToHighlight: "רדו למקום המדויק בעמוד",
    openExactPlace: "פתחו את העמוד באתר",
    closeSource: "סגירה",
    chooseThis: "זה הנכון",
    previewLoading: "טוענים את העמוד…",
    writeYourself: "או כתבו בעצמכם אם כלום למעלה לא מדויק",
    writeYourselfCta: "כתבו בעצמכם",
    notRelevant: "לא רלוונטי לחנות שלי",
    hiddenRejected: "משפטים שסומנו כלא נכון מוסתרים",
    showRejected: "הציגו אותם",
    hideRejected: "הסתירו",
    saveNext: "שמרו והמשיכו",
    backSection: "חזרה",
    chooseFirst: "בחרו או כתבו מה נכון",
    markedTrue: "סומן כנכון",
    markedFalse: "סומן כלא נכון",
    contradictsBadge: "גרסה נוספת",
    sureTitle: "את בטוחה?",
    sureRejectBody: "סימנת כנכון:\n“{approved}”\n\nלסמן את המשפט הזה כלא נכון?",
    sureApproveBody: "כבר סימנת משהו אחר כנכון:\n“{approved}”\n\nלסמן גם את זה כנכון? את עדיין מחליטה מה להשאיר, מה לא נכון, או לערוך — בלי שינוי אוטומטי.",
    sureRejectCta: "כן, זה לא נכון",
    sureApproveCta: "כן, גם זה נכון",
    sureKeepCta: "לא, להשאיר",
    sureCancel: "ביטול",
    recommendation: "המלצה לניסוח",
    canonicalLabel: "משפט מקור האמת",
    canonicalPlaceholder: "כתבו את המשפט שלקוחות — וגם ה-AI — צריכים לסמוך עליו.",
    writeHere: "מה לכתוב כאן",
    aiWhyLabel: "למה זה חשוב ל-AI",
    foundOnSite: "מה מצאנו באתר",
    downloadSection: "הורידו את הסקשן",
    copySection: "העתיקו את הסקשן",
    nextSection: "לסקשן הבא",
    sectionReady: "הסקשן מוכן כשמשפט מקור האמת כתוב.",
    downloadHint: "בסוף כל סקשן מורידים רק אותו. בסוף הכל — את כל המאגר.",
    openPage: "לעמוד",
    pagesRead: "עמודים שנקראו",
    all: "הכל",
    conflicts: "גרסאות",
    missingFilter: "חסר",
    approved: "אושר",
    pending: "לסקירה",
    knowledgeCta: "לדף שלכם",
    backToReview: "חזרה לסקירה",
    knowledgeEyebrow: "מאגר הידע",
    knowledgeTitle: "הורידו את מאגר הידע",
    knowledgeBody:
      "כל השאלות והתשובות שאישרתם — עם קישור למקום המדויק באתר.",
    publishStepsTitle: "מה לעשות עכשיו",
    publishStep1: "עברו על כל תשובה: זה נכון, זה לא נכון, או עריכה",
    publishStep2: "ליד כל שאלה: קישור לעמוד, וכפתור «ראו איפה בדיוק זה כתוב»",
    publishStep3: "בסוף הורידו את מאגר הידע",
    copyPage: "העתיקו את ה-HTML",
    downloadPage: "הורדת HTML",
    copyKb: "העתיקו JSON",
    copied: "הועתק",
    downloadKb: "הורדת JSON",
    downloadTxt: "הורדת טקסט",
    downloadPdf: "הורדת PDF",
    exportTitle: "מאגר הידע",
    exportBody: "הורידו את הכל בפורמט של Gemini — JSON, טקסט או PDF.",
    exportTitleDone: "הורידו את הכל",
    exportBodyDone: "אותו פורמט מאגר של Gemini: JSON לייבוא, טקסט, או PDF.",
    printPdfHint: "בחלון ההדפסה בחרו שמירה כ-PDF.",
    downloadMenu: "הורדה",
    guideCta: "איך זה עובד",
    guideTitle: "מה עושים כאן",
    guideBody: "Clarity קורא את האתר והופך אותו לשאלות. אתם רק מאשרים מה נכון — ואז מורידים את מאגר הידע.",
    guideSteps: [
      "סורקים את האתר של החנות, או ממשיכים טיוטה קיימת.",
      "ליד כל דבר: זה נכון, זה לא נכון, או עריכה — ואז שמור.",
      "ליד כל שאלה: קישור לעמוד באתר, וכפתור «ראו איפה בדיוק זה כתוב».",
      "בסוף לוחצים הורדה למעלה: JSON, טקסט או PDF.",
    ],
    guideGotIt: "הבנתי",
    pagePreview: "כך ייראה הדף",
    pagesToDelete: "עמודים למחוק מהאתר",
    pagesToDeleteBody: "העמודים האלה מפזרים את אותו מידע — או שעדיין כתוב בהם משהו שסימנתם כלא נכון. מחקו אותם אחרי שהדף החדש באוויר.",
    productCleanupTitle: "ניקוי המוצרים",
    productCleanupBody:
      "מצאנו מדיניות ב-{n} מוצרים. מחקו אותה מהתיאורים — משלוחים והחזרות שייכים לדף האחד.",
    productCleanupDownload: "הורדת רשימת הניקוי",
    removeFromProduct: "למחוק מהמוצר הזה",
    productCleanupExamples: "ראו דוגמאות",
    suggestedPath: "כתובת מוצעת",
    siteFixes: "עמודים לעדכון באתר",
    siteFixesBody: "בעמודים האלה עדיין כתוב משהו שסימנתם כלא נכון. נוסח מוצע להחלפה:",
    pagesToCreate: "סקשנים להוסיף באתר",
    pagesToCreateBody: "הסקשנים האלה חסרים. הוסיפו את העמוד, והשתמשו בנוסח הזה.",
    emptyKb: "אשרו לפחות משפט אחד כדי לבנות את מאגר הידע.",
    rescan: "סריקה של חנות אחרת",
    saveDraft: "שמרו טיוטה",
    draftSaved: "הטיוטה נשמרה",
    draftSavedHint: "לא מחוברים — נשמר רק בדפדפן הזה.",
    draftSavedCloudHint: "נשמר לחשבון.",
    draftSaveCloudError: "לא נשמר לחשבון. לחצו «שמרו טיוטה».",
    draftSavedAt: "נשמר לחשבון · {time}",
    signInGoogle: "המשיכו עם Google",
    signOut: "יציאה",
    signInTitle: "התחברות ל-Clarity",
    signInBody: "צרו חשבון או התחברו. אחר כך אפשר לסרוק חנות ולשמור טיוטה.",
    signInHint: "התחברו כדי להמשיך.",
    signInCta: "התחברות",
    authOr: "או עם שם משתמש וסיסמה",
    authLogin: "התחברות",
    authRegister: "הרשמה",
    authLoginCta: "התחברו",
    authRegisterCta: "צרו חשבון",
    authUsername: "שם משתמש",
    authPassword: "סיסמה",
    authWorking: "רגע…",
    authFailed: "לא הצלחנו להתחבר. נסו שוב.",
    authBadLogin: "שם משתמש או סיסמה שגויים.",
    authTaken: "שם המשתמש הזה תפוס.",
    authWeakPassword: "הסיסמה חייבת לפחות 6 תווים.",
    authInvalidUsername: "3–40 תווים: אותיות באנגלית, מספרים, . _ -",
    authNoDatabase: "שמירת חשבונות עדיין לא מחוברת. נסו שוב בעוד רגע.",
    topicQuestionsCount: "{n} שאלות",
    addedQuestions: "שאלות שהוספתם",
    savingCloud: "שומרים לחשבון…",
    productSectionBody: "סמנו מה רלוונטי במוצרים, ומה צריך לערוך.",
    productEditHint: "מה לערוך במוצר הזה",
    productNotes: "הערות למוצר הזה…",
    downloadDraft: "הורידו קובץ טיוטה",
    adminCta: "כל התשובות",
    adminTitle: "תשובות הסוחרים",
    adminBody: "כל שאלוני Clarity, כולל כאלה שנמחקו מהרשימה. אפשר להוריד JSON לחנות או את הכל יחד.",
    adminEmpty: "עדיין אין שאלונים.",
    adminDeleted: "נמחק מהרשימה שלהם",
    adminDownloadOne: "הורדת JSON",
    adminDownloadAll: "הורדת הכל",
    adminForbidden: "אין גישה לעמוד הזה.",
    categoryScan: "סריקה ממוקדת",
    categoryScanning: "סורקים את הקטגוריה…",
    categoryScanDone: "סריקה ממוקדת הסתיימה. בדקו נכון / לא נכון, והשלימו מה שחסר.",
    categoryScanMissing: "סריקה ממוקדת הסתיימה. ל־{n} שאלות עדיין אין כלום באתר — כתבו או סמנו לא נכון.",
    categoryScanNoAi: "מצאנו מה שיש באתר. כדי שה־AI ימלא תשובות חסרות, הוסיפו מפתח Gemini או OpenAI.",
    categoryScanError: "לא הצלחנו לסרוק את הקטגוריה. נסו שוב.",
    draftsTitle: "הטיוטות שלכם",
    draftsEmpty: "אין טיוטות בחשבון הזה. התחברו באותה דרך כמו במכשיר האחר — Google ושם משתמש הם חשבונות נפרדים.",
    signedInAs: "מחוברים כ־{name}",
    resumeDraft: "המשיכו",
    deleteDraft: "מחקו",
    deleteDraftTitle: "למחוק את השאלון?",
    deleteDraftBody: "הוא ייעלם מהרשימה שלכם, אבל יישאר שמור בחשבון.",
    deleteDraftConfirm: "כן, מחקו",
    deleteDraftCancel: "ביטול",
    backToDrafts: "חזרה לטיוטות",
    viewScroll: "גלילה",
    viewSlides: "סליידים",
    progressDone: "{done} מתוך {total}",
    progressLeft: "נשארו {n}",
    sectionComplete: "הסקשן הושלם!",
    allComplete: "סיימתם הכל!",
    prevSection: "הקודם",
    nextItem: "הבא",
    prevItem: "הקודם",
    importDraft: "טענו טיוטה או מאגר ידע (JSON)",
    draftPages: "{n} עמודים",
    draftJustNow: "עכשיו",
    errorTitle: "לא הצלחנו לסיים את הסריקה",
    errorInvalid: "הזינו כתובת אתר תקינה, למשל yourstore.co.il.",
    errorPrivate: "אי אפשר לסרוק את הכתובת הזו.",
    errorUnreachable: "לא הצלחנו להגיע לאתר. בדקו את האיות, או נסו עם www / בלי www.",
    errorBlocked: "האתר חסם גישה אוטומטית. נסו בלי www, או את כתובת Shopify (yourstore.myshopify.com).",
    errorEmpty: "האתר נפתח, אבל לא היה מספיק טקסט לקריאה.",
    errorTimeout: "האתר לקח יותר מדי זמן. נסו שוב בעוד רגע.",
    errorFailed: "הסריקה נכשלה. בדקו את הכתובת ונסו שוב.",
    tryDemo: "ראו דוגמה במקום",
    filterEmpty: "אין פריטים בתצוגה הזו עדיין.",
    demoBadge: "חנות לדוגמה",
    langToggle: "EN",
  },
} as const;
